package com.viene.actor;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class ActorSeeder implements ApplicationRunner {

    private final ActorRepository actorRepository;

    @Override
    public void run(ApplicationArguments args) {
        if (actorRepository.count() > 0) {
            return;
        }
        actorRepository.saveAll(sampleActors());
    }

    private List<Actor> sampleActors() {
        return List.of(
                Actor.builder()
                        .name("Ágora Tech Park")
                        .description("Parque tecnológico privado que promove o empreendedorismo e a inovação aberta, integrando o ecossistema.")
                        .category(ActorCategory.AMBIENTES)
                        .type(ActorType.PARQUE)
                        .city("Joinville")
                        .neighborhood("Distrito Industrial")
                        .latitude(-26.235347)
                        .longitude(-48.884955)
                        .address("Rua Dona Francisca, 8300, Distrito Industrial, Joinville")
                        .cep("89219-600")
                        .founded("2019")
                        .tags("Smart Cities (Cidades Inteligentes)")
                        .website("agoratechpark.com.br")
                        .phone("(47) 99932-5727")
                        .email("falecom@agoratechpark.com.br")
                        .linkedin("https://linkedin.com/company/agora-tech-park")
                        .instagram("https://instagram.com/agoratechpark")
                        .build(),
                Actor.builder()
                        .name("Fundação Softville")
                        .description("Entidade de fomento ao empreendedorismo, apoiando o surgimento e a consolidação de startups.")
                        .category(ActorCategory.AMBIENTES)
                        .type(ActorType.INCUBADORA)
                        .city("Joinville")
                        .neighborhood("Distrito Industrial")
                        .latitude(-26.235347)
                        .longitude(-48.884955)
                        .address("Rua Dona Francisca, 8300, Distrito Industrial, Joinville")
                        .cep("89219-600")
                        .founded("1995")
                        .tags("Indústria 4.0 & Manufatura Avançada")
                        .website("softville.org.br")
                        .phone("(47) 3439-0666")
                        .email("contato@softville.org.br")
                        .linkedin("https://linkedin.com/company/softville")
                        .instagram("https://instagram.com/softville")
                        .build(),
                Actor.builder()
                        .name("FabLab Joinville")
                        .description("Laboratório aberto focado em prototipagem rápida, educação maker e fabricação digital.")
                        .category(ActorCategory.AMBIENTES)
                        .type(ActorType.MAKER)
                        .city("Joinville")
                        .neighborhood("Centro")
                        .latitude(-26.302089)
                        .longitude(-48.845734)
                        .address("Rua do Príncipe, 330, Centro, Joinville")
                        .cep("89201-900")
                        .founded("2016")
                        .tags("Impressão 3D & Manufatura Aditiva")
                        .website("fablabjoinville.com.br")
                        .phone("(47) 98877-6655")
                        .email("ola@fablabjoinville.com.br")
                        .instagram("https://instagram.com/fablabjlle")
                        .build(),
                Actor.builder()
                        .name("Opa Coworking")
                        .description("Espaço de trabalho compartilhado e networking para profissionais independentes e startups.")
                        .category(ActorCategory.AMBIENTES)
                        .type(ActorType.COWORKING)
                        .city("Joinville")
                        .neighborhood("Atiradores")
                        .latitude(-26.301387)
                        .longitude(-48.851431)
                        .address("Rua Otto Boehm, 15, Atiradores, Joinville")
                        .cep("89201-700")
                        .founded("2018")
                        .tags("Smart Cities (Cidades Inteligentes)")
                        .build(),
                Actor.builder()
                        .name("Conta Azul")
                        .description("Desenvolve software ERP na nuvem para gestão de MPEs.")
                        .category(ActorCategory.PRIVADO)
                        .type(ActorType.CORPORACAO)
                        .city("Joinville")
                        .neighborhood("Distrito Industrial")
                        .latitude(-26.235347)
                        .longitude(-48.884955)
                        .address("Rua Dona Francisca, 8300, Distrito Industrial, Joinville")
                        .cep("89219-600")
                        .founded("2012")
                        .tags("FinTech")
                        .website("contaazul.com")
                        .phone("(47) 3461-4100")
                        .email("contato@contaazul.com")
                        .linkedin("https://linkedin.com/company/contaazul")
                        .instagram("https://instagram.com/contaazul")
                        .youtube("https://youtube.com/@contaazul")
                        .build(),
                Actor.builder()
                        .name("Asaas")
                        .description("Fintech que automatiza rotinas financeiras e gestão de assinaturas.")
                        .category(ActorCategory.PRIVADO)
                        .type(ActorType.STARTUP)
                        .city("Joinville")
                        .neighborhood("Bom Retiro")
                        .latitude(-26.252028)
                        .longitude(-48.853002)
                        .address("Av. Rolf Wiest, 277, Bom Retiro, Joinville")
                        .cep("89223-005")
                        .founded("2013")
                        .tags("FinTech")
                        .website("asaas.com")
                        .phone("0800 005 3225")
                        .email("contato@asaas.com.br")
                        .linkedin("https://linkedin.com/company/asaas")
                        .instagram("https://instagram.com/asaas.brasil")
                        .youtube("https://youtube.com/@AsaasGestaoFinanceira")
                        .build(),
                Actor.builder()
                        .name("UNIVILLE")
                        .description("Instituição de Ensino Superior comunitária com forte atuação em pesquisa científica.")
                        .category(ActorCategory.EDUCACAO)
                        .type(ActorType.IES)
                        .city("Joinville")
                        .neighborhood("Bom Retiro")
                        .latitude(-26.2517)
                        .longitude(-48.856148)
                        .address("Rua Paulo Malschitzki, 10, Bom Retiro, Joinville")
                        .cep("89219-710")
                        .founded("1965")
                        .tags("Biotecnologia & Nanotecnologia")
                        .website("univille.edu.br")
                        .phone("0800 643 8800")
                        .email("reitoria@univille.br")
                        .linkedin("https://linkedin.com/school/univille")
                        .instagram("https://instagram.com/univille")
                        .youtube("https://youtube.com/@univille")
                        .build(),
                Actor.builder()
                        .name("SENAI Joinville")
                        .description("Referência em formação técnica e profissional voltada à indústria.")
                        .category(ActorCategory.EDUCACAO)
                        .type(ActorType.TECNICO)
                        .city("Joinville")
                        .neighborhood("Santo Antônio")
                        .latitude(-26.263565)
                        .longitude(-48.861595)
                        .address("Rua Arno W. Döhler, 16, Santo Antônio, Joinville")
                        .cep("89218-155")
                        .founded("1943")
                        .tags("Indústria 4.0 & Manufatura Avançada")
                        .website("sc.senai.br")
                        .phone("(47) 3441-7700")
                        .email("joinville@sc.senai.br")
                        .linkedin("https://linkedin.com/school/senai-sc")
                        .instagram("https://instagram.com/senai.sc")
                        .build(),
                Actor.builder()
                        .name("Sec. de Inovação de Joinville (SDE)")
                        .description("Secretaria municipal que atua em políticas de fomento econômico e modernização da cidade.")
                        .category(ActorCategory.PUBLICO)
                        .type(ActorType.GOVERNO)
                        .city("Joinville")
                        .neighborhood("Centro")
                        .latitude(-26.300929)
                        .longitude(-48.840707)
                        .address("Av. Hermann August Lepper, 10, Centro, Joinville")
                        .cep("89221-005")
                        .founded("1851")
                        .tags("Smart Cities (Cidades Inteligentes)")
                        .website("joinville.sc.gov.br")
                        .phone("(47) 3431-3233")
                        .email("sde@joinville.sc.gov.br")
                        .linkedin("https://linkedin.com/company/prefeituradejoinville")
                        .instagram("https://instagram.com/prefeituradejoinville")
                        .build(),
                Actor.builder()
                        .name("Sebrae Joinville")
                        .description("Apoia micro e pequenas empresas com foco em gestão, inovação e competitividade.")
                        .category(ActorCategory.PUBLICO)
                        .type(ActorType.FOMENTO)
                        .city("Joinville")
                        .neighborhood("Centro")
                        .latitude(-26.301652)
                        .longitude(-48.84539)
                        .address("Rua do Príncipe, 348, Centro, Joinville")
                        .cep("89201-900")
                        .founded("1972")
                        .tags("RetailTech")
                        .website("sebrae.com.br")
                        .phone("(47) 3406-0800")
                        .email("atendimento@sebraesc.com.br")
                        .linkedin("https://linkedin.com/company/sebrae-sc")
                        .instagram("https://instagram.com/sebraesc")
                        .build());
    }
}
